language: julia
os:
    - linux
    - osx
julia:
    - 0.7
    - 1.0
    - 1.1
	- 1.3
    - nightly
addons:
#  apt:
#    packages:
#        - hdf5-tools
before_script:
#    - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; brew link --overwrite gcc; brew install hdf5; fi
notifications:
    email: false
after_success:
    - julia -e 'cd(Pkg.dir("MAT")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
